[package]
name = "konst"
version = "0.2.0"
authors = ["rodrimati1992 <rodrimatt1985@gmail.com>"]
edition = "2018"
license = "Zlib"
description = "Compile-time comparison, parsing, and other const functionality"
documentation = "https://docs.rs/konst/"
readme="../README.md"
keywords = ["no-std"]
categories = ["no-std"]
repository = "https://github.com/rodrimati1992/konst/"
include = [
    "Cargo.toml", 
    "src/**/*.rs", 
    "../README.md",
    "../LICENSE-ZLIB.md", 
]

[dependencies.konst_proc_macros]
version = "=0.2.0"
path = "../konst_proc_macros"
optional = true


[features]
default = ["cmp", "parsing"]

cmp = []
parsing = ["parsing_no_proc", "konst_proc_macros"]
parsing_no_proc = []
constant_time_slice = []
const_generics = []

docsrs = []



[package.metadata.docs.rs]
features = ["docsrs", "cmp", "parsing"]

