[package]
name = "konst"
version = "0.2.19"
authors = ["rodrimati1992 <rodrimatt1985@gmail.com>"]
edition = "2018"
license = "Zlib"
description = "Const equivalents of std functions, compile-time comparison, and parsing"
documentation = "https://docs.rs/konst/"
readme="../README.md"
keywords = ["no-std", "const_fn", "parsing"]
categories = ["no-std", "parsing"]
repository = "https://github.com/rodrimati1992/konst/"
include = [
    "Cargo.toml", 
    "src/**/*.rs", 
    "../README.md",
    "LICENSE-ZLIB.md", 
]


[dependencies.konst_proc_macros]
version = "=0.2.11"
path = "../konst_proc_macros"
optional = true

[dependencies.konst_macro_rules]
version = "=0.2.19"
path = "../konst_macro_rules"

[dev-dependencies.rand]
version = "0.8.4"
default-features = false
features = ["small_rng"]

[dev-dependencies.trybuild]
version = "1.0"

[features]
default = ["cmp", "parsing"]

cmp = []
parsing = ["parsing_no_proc", "konst_proc_macros"]
parsing_no_proc = []
const_generics = ["rust_1_51"]
rust_1_51 = ["konst_macro_rules/rust_1_51"]
rust_1_55 = ["rust_1_51", "konst_macro_rules/rust_1_55"]
rust_1_56 = ["rust_1_55", "konst_macro_rules/rust_1_56"]
rust_1_57 = ["rust_1_56", "konst_macro_rules/rust_1_57"]
rust_1_61 = ["rust_1_57", "konst_macro_rules/rust_1_61"]
rust_1_64 = ["rust_1_61"]
rust_latest_stable = ["rust_1_64"]
deref_raw_in_fn = ["rust_1_56"]
constant_time_slice = ["rust_latest_stable"]
mut_refs = ["rust_latest_stable", "konst_macro_rules/mut_refs"]
nightly_mut_refs = ["mut_refs", "konst_macro_rules/nightly_mut_refs"]

alloc = []

# Using doctests to ensure that some stuff does/doesn't compile
__test = []

docsrs = []



[package.metadata.docs.rs]
features = ["docsrs", "alloc", "cmp", "parsing", "rust_latest_stable", "nightly_mut_refs"]

