[package]
name = "konst"
version = "0.2.9"
authors = ["rodrimati1992 <rodrimatt1985@gmail.com>"]
edition = "2018"
license = "Zlib"
description = "Compile-time comparison, parsing, and other const functionality"
documentation = "https://docs.rs/konst/"
readme="../README.md"
keywords = ["no-std", "const_fn", "parsing"]
categories = ["no-std", "parsing"]
repository = "https://github.com/rodrimati1992/konst/"
include = [
    "Cargo.toml", 
    "src/**/*.rs", 
    "../README.md",
    "../LICENSE-ZLIB.md", 
]

[dependencies.konst_proc_macros]
version = "=0.2.0"
path = "../konst_proc_macros"
optional = true

[dependencies.konst_macro_rules]
version = "=0.2.9"
path = "../konst_macro_rules"

[features]
default = ["cmp", "parsing"]

cmp = []
parsing = ["parsing_no_proc", "konst_proc_macros"]
parsing_no_proc = []
constant_time_slice = []
const_generics = ["konst_macro_rules/const_generics"]
deref_raw_in_fn = ["const_generics", "konst_macro_rules/deref_raw_in_fn"]
nightly_mut_refs = ["mut_refs", "konst_macro_rules/nightly_mut_refs"]
mut_refs = ["deref_raw_in_fn", "konst_macro_rules/mut_refs"]




alloc = []

# Using doctests to ensure that some stuff does/doesn't compile
__test = []

docsrs = []



[package.metadata.docs.rs]
features = ["docsrs", "alloc", "cmp", "parsing", "const_generics", "deref_raw_in_fn", "nightly_mut_refs"]

